name: commit-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/setup-and-build.yml

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
