name: pull-request

on:
  pull_request:
    

jobs:
  build:
    uses: ./.github/workflows/setup-and-build.yml

  quality-checks:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          dest: ~/setup-pnpm
          run_install: false
          package_json_file: package.json
          standalone: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

      - name: Run static type check
        run: pnpm tsc --noEmit

      - name: Run unit tests
        run: pnpm test
